### ISSUE TITLE
search process instances with/without incidents

### ISSUE THREAD

**Issue by nhomble** [camunda-community-hub/operate-client-node-js#3]
The examples show that you can search and filder for open instances without incidents by providing a boolean `incidents` flag to the search query. The interface in this lib doesn't support this.

**Comment by jwulf** [comment]
This only works on the Flow Node. A Query filter for an object `T` is a `Partial<T>`. 

There is a misprint in the docs - it should be `incident: boolean`, which is a field of `FlownodeInstance`.
